import type { Metadata } from "next";

import { CopilotKitProvider } from "@copilotkitnext/react";
import "./globals.css";
import "@copilotkitnext/react/styles.css";
import { weatherToolRenderer } from "./components/gen-ui/weather";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <CopilotKitProvider
          renderToolCalls={[weatherToolRenderer]}
          runtimeUrl="/api/copilotkit"
        >
          {children}
        </CopilotKitProvider>
      </body>
    </html>
  );
}
